apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
      app: database
  ports:
      - port: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
    selector:
        app: frontend
    ports:
      - port: 8088
        targetPort: 80
    type: LoadBalancer