apiVersion: v1
kind: Service
metadata:
  name: super-mario-service
spec:
  selector:
    app: super-mario
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
spec:
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: LoadBalancer